version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ubuntu-ami.json
      - run:
          name: build ami
          command: packer build ubuntu-ami.json

workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build